-- MySQL Script generated by MySQL Workbench
-- Sun Nov 19 04:00:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AssistenciaTecnica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AssistenciaTecnica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AssistenciaTecnica` DEFAULT CHARACTER SET utf8 ;
USE `AssistenciaTecnica` ;

-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`tecnico` (
  `cod.tecnico` INT NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `nometec` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod.tecnico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`cliente` (
  `cpf` INT NOT NULL,
  `cod.cli` INT NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`, `cod.cli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`equipamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`equipamentos` (
  `cod.equi` INT NOT NULL,
  `defeito.equi` VARCHAR(45) NOT NULL,
  `configuracao.equi` VARCHAR(45) NOT NULL,
  `cliente_cpf` INT NOT NULL,
  `cliente_cod.cli` INT NOT NULL,
  `tecnico_cod.tecnico` INT NOT NULL,
  PRIMARY KEY (`cod.equi`, `cliente_cpf`, `cliente_cod.cli`, `tecnico_cod.tecnico`),
  INDEX `fk_equipamentos_cliente_idx` (`cliente_cpf` ASC, `cliente_cod.cli` ASC),
  INDEX `fk_equipamentos_tecnico1_idx` (`tecnico_cod.tecnico` ASC),
  CONSTRAINT `fk_equipamentos_cliente`
    FOREIGN KEY (`cliente_cpf` , `cliente_cod.cli`)
    REFERENCES `AssistenciaTecnica`.`cliente` (`cpf` , `cod.cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipamentos_tecnico1`
    FOREIGN KEY (`tecnico_cod.tecnico`)
    REFERENCES `AssistenciaTecnica`.`tecnico` (`cod.tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`servicos` (
  `cod.serv` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `orcamento` INT NOT NULL,
  `realizados.serv` VARCHAR(45) NOT NULL,
  `equipamentos_cod.equi` INT NOT NULL,
  `equipamentos_cliente_cpf` INT NOT NULL,
  `equipamentos_cliente_cod.cli` INT NOT NULL,
  `equipamentos_tecnico_cod.tecnico` INT NOT NULL,
  PRIMARY KEY (`cod.serv`, `equipamentos_cod.equi`, `equipamentos_cliente_cpf`, `equipamentos_cliente_cod.cli`, `equipamentos_tecnico_cod.tecnico`),
  INDEX `fk_servicos_equipamentos1_idx` (`equipamentos_cod.equi` ASC, `equipamentos_cliente_cpf` ASC, `equipamentos_cliente_cod.cli` ASC, `equipamentos_tecnico_cod.tecnico` ASC),
  CONSTRAINT `fk_servicos_equipamentos1`
    FOREIGN KEY (`equipamentos_cod.equi` , `equipamentos_cliente_cpf` , `equipamentos_cliente_cod.cli` , `equipamentos_tecnico_cod.tecnico`)
    REFERENCES `AssistenciaTecnica`.`equipamentos` (`cod.equi` , `cliente_cpf` , `cliente_cod.cli` , `tecnico_cod.tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`pagamento` (
  `servicos_cod.serv` INT NOT NULL,
  `servicos_equipamentos_cod.equi` INT NOT NULL,
  `servicos_equipamentos_cliente_cpf` INT NOT NULL,
  `servicos_equipamentos_cliente_cod.cli` INT NOT NULL,
  `servicos_equipamentos_tecnico_cod.tecnico` INT NOT NULL,
  `tecnico_cod.tecnico` INT NOT NULL,
  PRIMARY KEY (`servicos_cod.serv`, `servicos_equipamentos_cod.equi`, `servicos_equipamentos_cliente_cpf`, `servicos_equipamentos_cliente_cod.cli`, `servicos_equipamentos_tecnico_cod.tecnico`, `tecnico_cod.tecnico`),
  INDEX `fk_pagamento_tecnico1_idx` (`tecnico_cod.tecnico` ASC),
  CONSTRAINT `fk_pagamento_servicos1`
    FOREIGN KEY (`servicos_cod.serv` , `servicos_equipamentos_cod.equi` , `servicos_equipamentos_cliente_cpf` , `servicos_equipamentos_cliente_cod.cli` , `servicos_equipamentos_tecnico_cod.tecnico`)
    REFERENCES `AssistenciaTecnica`.`servicos` (`cod.serv` , `equipamentos_cod.equi` , `equipamentos_cliente_cpf` , `equipamentos_cliente_cod.cli` , `equipamentos_tecnico_cod.tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_tecnico1`
    FOREIGN KEY (`tecnico_cod.tecnico`)
    REFERENCES `AssistenciaTecnica`.`tecnico` (`cod.tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
